apiVersion: v2
name: helm-webserver
version: 0.1.0
appVersion: 1.0.0
description: A helm chart for nxtgenhub weberver using nginx

dependencies:
  # - name: traefik
  #   version: "*" # 13.x.x
  #   repository: "https://traefik.github.io/charts"
  - name: ingress-nginx
    version: "*" # 4.x.x
    repository: "https://kubernetes.github.io/ingress-nginx"
