# name: nxtgen-webserver
replicaCount: 1
image:
  repository: eyodevops/nxtgenhub-webserver
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  ingressClassName: nginx
  enabled: true
  host: "nxtgenhub.eyoghanatest.site"
  annotations: {}
  clusterIssuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "letsencrypt-prod"

namespace: "nxtgenhub-helm" # Namespace for the deployment
