apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nxtgen-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
