apiVersion: v1
kind: Service
metadata:
  name: nxtgen-webserver-svc
  namespace: nxtgenhub
spec:
  selector:
    app: nxtgen-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
