# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-nxtgen
spec:
  secretName: www-nxtgen-tls
  revisionHistoryLimit: 1
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: www.nxtgenhub.eyoghanatest.site
  dnsNames:
    - www.nxtgenhub.eyoghanatest.site
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
