apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: eyo.techsolutions@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
      # - dns01:
      #     route53:
      #       region: eu-north-1
      #       role: arn:aws:iam::837538001765:role/cert-manager-acme-dns01-route53
      #       auth:
      #         kubernetes:
      #           serviceAccountRef:
      #             name: cert-manager-acme-dns01-route53

---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: eyo.techsolutions@gmail.com
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: letsencrypt-prod
#     # Enable the HTTP-01 challenge provider
#     solvers:
#       - http01:
#           ingress:
#             ingressClassName: nginx
